### ISSUE TITLE
Allow people to pass their own filebeat config file

### ISSUE THREAD

**Issue by AndresPineros** [geerlingguy/ansible-role-filebeat#35]
Hello,

You could just allow passing the filebeat.yml file via the playbook. Matching all possible variables or trying to externalize all the filebeat config to allow parametrizing from the playbook as "vars" is going to be very hard.

A very easy way could be doing something like:
```
- name: get file stat to be able to perform a check in the following tasks
  local_action: stat path={{ playbook_dir }}/filebeat/filebeat.yml.j2
  register: file

- name: Copy Filebeat configuration.
  template:
    src: "filebeat.yml.j2"
    dest: "/etc/filebeat/filebeat.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart filebeat
  when: not file.stat.exists

- name: Copy Filebeat configuration (provided).
  template:
    src: "{{ playbook_dir }}/filebeat/filebeat.yml.j2"
    dest: "/etc/filebeat/filebeat.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart filebeat
  when: file.stat.exists
```
I know this means an extra file, but this will make things easier. Less maintenance trying to make everything configurable and less people forking to make their own filebeat.yml.j2.

This can even be optional. If you don't want to pass your own file, then work with the default .j2 and its externalized variables.
