### ISSUE TITLE
broken configurations

### ISSUE THREAD

**Issue by jvzantvoort** [geerlingguy/ansible-role-filebeat#42]
Host machine os: CentOS Linux release 7.6.1810 (Core)
Filebeat package version: filebeat-6.8.0-1.x86_64

Example configuration:
```
---
- hosts: demohost

  roles:
    - role: geerlingguy.filebeat
      vars:
        filebeat_output_elasticsearch_enabled: true
        filebeat_output_elasticsearch_hosts:
          - "10.1.1.199:9200"
        filebeat_prospectors:
          - input_type: log
            paths:
              - "/var/log/*.log"
```
Playbook runs without issue. However resulting configuration fails:
```
[root@elkclient ~]# filebeat test config
Exiting: error unpacking config data: more than one namespace configured accessing 'output' (source:'/etc/filebeat/filebeat.yml')
```

Format does not seem to be matching the source configuration **at-all**. 

I'd suggest adding the "filebeat test config" command as a step when ```filebeat_create_config``` is set to ```true```. This allows the playbook to fail when the configuration is managed and it fails.
