### ISSUE TITLE
RH9 fails to import elastic gpg key due to crypto policy.

### ISSUE THREAD

**Issue by ryanbarrett** [geerlingguy/ansible-role-filebeat#66]
Ran across an issue in Alma 9 (assuming the other variants of 9 as well) where the crypto policy does not allow the import of the elastic key due to its SHA1 signature. 

```
TASK [geerlingguy.filebeat : Add Elasticsearch GPG key.] ********************************************************************************************************************************************
fatal: [xxx.xxx.xxx.xxx]: FAILED! => {"changed": false, "msg": "error: /tmp/tmptfcvb_bz: key 1 import failed.\n"}
```

**Workaround**
I'm not quite skilled enough with ansible to suggest a fix, but I've found a workaround that should work for RH9 variants.
Temporarily reduces security but enables functionality.

https://almalinux.discourse.group/t/unable-to-import-a-gpg-key-on-almalinux-9/1235

```
pre_tasks:
    - name: Set legacy crypto policy for filebeat install
      ansible.builtin.command: update-crypto-policies --set DEFAULT:SHA1

roles:
    - geerlingguy.filebeat

post_tasks:
    - name: Reset crypto policy to default.
      ansible.builtin.command: update-crypto-policies --set DEFAULT
```
