### ISSUE TITLE
Copy CA file during SSL configuration as well

### ISSUE THREAD

**Issue by pfoof** [geerlingguy/ansible-role-filebeat#68]
Shouldn't the CA file be copied as well?

https://github.com/geerlingguy/ansible-role-filebeat/blob/master/tasks/config.yml#L21

I specified the following:

```
filebeat_ssl_certs_dir: /etc/filebeat
filebeat_ssl_private_dir: /etc/filebeat
filebeat_ssl_ca_cert_file: ca-cert.pem
filebeat_ssl_certificate_file: mycert.pem
filebeat_ssl_key_file: mykey.pem
filebeat_ssl_copy_file: true
```

And the resulting config part is:
```
ssl:
  certificate_authorities: ["/etc/filebeat/ca-cert.pem"]
  certificate: "/etc/filebeat/mycert.pem"
  key: "/etc/filebeat/mykey.pem"
```

But `ca-cert.pem` does not exist in `/etc/filebeat`
