### ISSUE TITLE
Invalid jinja2 template syntax

### ISSUE THREAD

**Issue by sc68cal** [geerlingguy/ansible-role-filebeat#79]
#76 appears to have issues, when providing a username and password the username gets put at the end on the commented line.

```yaml
    # Optional auth via API Key or username/password.
    # The options are mutually exclusive and api_key takes the precedence.username: "<my username>"
    password: "<my password>"
    # Number of workers per Elasticsearch host.
    #worker: 1
```

Configuration:

```yaml

    filebeat_output_elasticsearch_auth:
        username: "<my username>"
        password: "<my password>"
```
